channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - boost-cpp=1.72.0=h7b93d67_2
  - bzip2=1.0.8=h516909a_3
  - c-ares=1.16.1=h516909a_3
  - ca-certificates=2020.6.20=hecda079_0
  - cairo=1.16.0=h3fc0475_1005
  - cfitsio=3.470=hce51eda_6
  - curl=7.71.1=he644dc0_5
  - dbus=1.13.6=he372182_0
  - expat=2.2.9=he1b5a44_2
  - fontconfig=2.13.1=h1056068_1002
  - freetype=2.10.2=he06d7ca_0
  - freexl=1.0.5=h516909a_1002
  - geos=3.8.1=he1b5a44_0
  - geotiff=1.6.0=ha04d9d0_1
  - gettext=0.19.8.1=hc5be6a0_1002
  - giflib=5.2.1=h516909a_2
  - glib=2.65.0=h6f030ca_0
  - gst-plugins-base=1.14.5=h0935bb2_2
  - gstreamer=1.14.5=h36ae1b5_2
  - hdf4=4.2.13=hf30be14_1003
  - hdf5=1.10.6=nompi_h3c11f04_101
  - icu=67.1=he1b5a44_0
  - jpeg=9d=h516909a_0
  - json-c=0.13.1=hbfbb72e_1002
  - kealib=1.4.13=h33137a7_1
  - krb5=1.17.1=hfafb76e_3
  - ld_impl_linux-64=2.34=hc38a660_9
  - libblas=3.8.0=17_openblas
  - libcblas=3.8.0=17_openblas
  - libclang=10.0.1=default_hde54327_1
  - libcurl=7.71.1=hcdd3856_5
  - libdap4=3.20.6=h1d1bd15_1
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libevent=2.1.10=hcdb4288_2
  - libffi=3.2.1=he1b5a44_1007
  - libgcc-ng=9.3.0=h24d8f2e_16
  - libgdal=3.1.2=hb2a6f5f_2
  - libgfortran-ng=7.5.0=hdf63c60_16
  - libglu=9.0.0=he1b5a44_1001
  - libgomp=9.3.0=h24d8f2e_16
  - libiconv=1.16=h516909a_0
  - libkml=1.3.0=hb574062_1011
  - liblapack=3.8.0=17_openblas
  - libllvm10=10.0.1=he513fc3_3
  - libnetcdf=4.7.4=nompi_h84807e1_105
  - libnghttp2=1.41.0=h8cfc5f6_2
  - libopenblas=0.3.10=pthreads_hb3c22a3_4
  - libpng=1.6.37=hed695b0_2
  - libpq=12.3=h5513abc_0
  - libspatialite=4.3.0a=h57f1b35_1039
  - libssh2=1.9.0=hab1572f_5
  - libstdcxx-ng=9.3.0=hdf63c60_16
  - libtiff=4.1.0=hc7e4089_6
  - libuuid=2.32.1=h14c3975_1000
  - libwebp-base=1.1.0=h516909a_3
  - libxcb=1.13=h14c3975_1002
  - libxkbcommon=0.10.0=he1b5a44_0
  - libxml2=2.9.10=h68273f3_2
  - lz4-c=1.9.2=he1b5a44_3
  - mysql-common=8.0.21=1
  - mysql-libs=8.0.21=hf3661c5_1
  - ncurses=6.2=he1b5a44_1
  - nspr=4.28=he1b5a44_0
  - nss=3.56=he751ad9_0
  - openjpeg=2.3.1=h981e76c_3
  - openssl=1.1.1g=h516909a_1
  - pcraster=4.3.0=py37hc9c97c7_4
  - pcre=8.44=he1b5a44_0
  - pixman=0.38.0=h516909a_1003
  - poppler=0.89.0=h4190859_1
  - poppler-data=0.4.9=1
  - postgresql=12.3=h8573dbc_0
  - proj=7.1.0=h966b41f_1
  - pthread-stubs=0.4=h14c3975_1001
  - python=3.7.8=h6f2ec95_1_cpython
  - python_abi=3.7=1_cp37m
  - qt=5.12.9=h1f2b2cb_0
  - readline=8.0=he28a2e2_2
  - setuptools=49.6.0=py37hc8dfbb8_0
  - sqlite=3.33.0=h4cf870e_0
  - tbb=2020.2=hc9558a2_0
  - tiledb=2.0.8=h3effe38_0
  - tk=8.6.10=hed695b0_0
  - tzcode=2020a=h516909a_0
  - wheel=0.35.1=pyh9f0ad1d_0
  - xerces-c=3.2.3=hfe33f54_1
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.12=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.5=h516909a_1
  - zlib=1.2.11=h516909a_1009
  - zstd=1.4.5=h6597ccf_2
  - pip
  - pip:
    - atomicwrites==1.3.0
    - attrs==19.3.0
    - backcall==0.1.0
    - beautifulsoup4==4.8.1
    - bleach==3.1.1
    - certifi==2019.11.28
    - cffi==1.14.3
    - cftime==1.0.4.2
    - chardet==3.0.4
    - colorama==0.4.3
    - coverage==5.0.3
    - cryptography==3.1.1
    - cython==0.29.14
    - dask==2.7.0
    - decorator==4.4.1
    - docopt==0.6.2
    - docutils==0.15.2
    - entrypoints==0.3
    - filelock==3.0.12
    - flake8==3.7.9
    - future==0.18.0
    - future-fstrings==1.2.0
    - gdal==3.1.2
    - gitdb2==2.0.6
    - graphtools==1.4.1
    - idna==2.8
    - importlib-metadata==0.23
    - iniconfig==1.0.1
    - ipython-genutils==0.2.0
    - jedi==0.15.1
    - jeepney==0.4.3
    - joblib==0.14.1
    - keyring==21.4.0
    - lisflood-utilities==0.12.9
    - lxml==4.4.1
    - mccabe==0.6.1
    - meld==0.2.4
    - more-itertools==7.2.0
    - netcdf4==1.5.3
    - nine==1.0.0
    - numexpr==2.7.0
    - numpy==1.18.3
    - packaging==19.2
    - pandas==0.25.1
    - parso==0.5.1
    - pathlib2==2.3.5
    - pexpect==4.7.0
    - pickleshare==0.7.5
    - pip==20.2.3
    - pkginfo==1.5.0.1
    - pluggy==0.13.0
    - prompt-toolkit==2.0.10
    - ptyprocess==0.6.0
    - py==1.8.0
    - pycodestyle==2.5.0
    - pycparser==2.20
    - pyflakes==2.1.1
    - pygments==2.4.2
    - pygsp==0.5.1
    - pyparsing==2.4.2
    - pyproj==2.4.0
    - pytest==5.2.1
    - pytest-cov==2.8.1
    - pytest-env==0.6.2
    - pytest-mock==2.0.0
    - python-dateutil==2.8.1
    - pytz==2019.3
    - pyyaml==5.3
    - readme-renderer==24.0
    - requests==2.24.0
    - requests-toolbelt==0.9.1
    - rfc3986==1.4.0
    - scikit-learn==0.23.2
    - scipy==1.4.0
    - scprep==1.0.3
    - secretstorage==3.1.2
    - six==1.12.0
    - smmap2==2.0.5
    - soupsieve==1.9.5
    - tasklogger==1.0.0
    - threadpoolctl==2.1.0
    - toml==0.10.0
    - toolz==0.10.0
    - tox==3.14.0
    - tqdm==4.36.1
    - traitlets==4.3.3
    - twine==3.2.0
    - urllib3==1.25.6
    - virtualenv==16.7.6
    - wcwidth==0.1.7
    - webencodings==0.5.1
    - xarray==0.15.1
    - zipp==0.6.0
